spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/findserv_api
    username: postgres
    password: admin123
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
  port: 8090
